child_repository_refactoring
belnarto/kindergarten pull request #25
Opened 2022-08-23 13:58 UTC by AlexeiRabushko

child repository refactoring

2022-08-23 14:03 UTC, AlexeiRabushko commented
> рефакторинг дочернего репозитория

code formatting in a project

2022-08-23 20:19 UTC, AlexeiRabushko reviewed
conflict settled

2022-08-24 12:25 UTC, belnarto requested changes

2022-08-24 12:25 UTC, belnarto commented on src/main/java/com/example/kindergarten/service/ChildServiceImpl.java
> +child_repository_refactoring
??

2022-08-24 12:25 UTC, belnarto commented on src/main/java/com/example/kindergarten/service/ChildServiceImpl.java
> + child_repository_refactoring
??

2022-08-24 12:25 UTC, belnarto commented on src/main/java/com/example/kindergarten/service/ChildServiceImpl.java
> +
why do we need extra empty lines here?

2022-08-24 12:25 UTC, belnarto commented on src/main/java/com/example/kindergarten/service/ChildServiceImpl.java
> +
????

2022-08-26 04:57 UTC, belnarto approved these changes

2022-08-26 04:58 UTC, merged