added package enums
belnarto/kindergarten pull request #30
Opened 2022-08-29 10:20 UTC by AlexeiRabushko

2022-08-29 11:08 UTC, belnarto requested changes

2022-08-29 11:08 UTC, belnarto commented on src/main/java/com/example/kindergarten/dto/ChildDto.java
> +    private Gender sex;
давай переменную назовём gender

2022-08-29 11:08 UTC, belnarto commented on src/main/java/com/example/kindergarten/dto/ChildDto.java
> +    private Gender sex;
NotNull решил не добавлять?

2022-08-29 11:08 UTC, belnarto commented on src/main/java/com/example/kindergarten/enums/Gender.java
> +@Getter
форматирование

2022-08-29 11:08 UTC, belnarto commented on src/main/java/com/example/kindergarten/enums/Gender.java
> +
форматирвоание

2022-08-29 11:08 UTC, belnarto commented on src/main/java/com/example/kindergarten/enums/Gender.java
> +
форматирование

2022-08-29 14:07 UTC, AlexeiRabushko reviewed
added gender child

2022-08-29 14:26 UTC, AlexeiRabushko reviewed
rename column

2022-08-29 17:59 UTC, YuryBonch approved these changes

2022-08-30 03:51 UTC, belnarto approved these changes

2022-08-30 03:52 UTC, merged